### ISSUE TITLE
[Bug] missing an arrow in architecture picture

### ISSUE THREAD

**Issue by daywednes** [libra/website#24]
# 🐛 Bug

We should have an arrow for 10 (Execution to Consensus) on the architectural components image. https://developers.libra.org/docs/life-of-a-transaction#lifecycle-of-the-transaction

## Steps to reproduce

Draw an arrow for that.

**Comment by gc3** [comment]
Thanks for your report! We'll fix it as soon as we can.

**Comment by gc3** [comment]
We took a look, and it seems like this expected. The arrow is going one way as following the NOTE section in this part of the doc : https://developers.libra.org/docs/life-of-a-transaction#validator-component-interactions

**Comment by mikedoan** [comment]
I may be wrong but read this

_10 — After executing the transactions in the block, the execution component appends the transactions in the block (including T5) to the Merkle accumulator (of the ledger history). This is an in-memory/temporary version of the Merkle accumulator. The (proposed/speculative) result of executing these transactions is returned to the consensus component. (Consensus → Execution CO.3, EX.1)_ --> should be **Execution -> Consensus** instead of **Consensus → Execution CO.3, EX.1**

**Comment by kphfb** [comment]
@mikedoan agree that it is quite confusing.  The initial intention of the arrows was to show which component calls the other, which in this case would show consensus -> execution, but that is fairly confusing in this case.  We could potentially merge 8, 9, 10 - but that will result in a fairly lengthy paragraph.  We could also change "(Consensus → Execution CO.3, EX.1)" to simply be "(CO.3, EX.1)".  Will try to find something that clears it up some today.

**Comment by archjayas** [comment]
@mikedoan, a fix is on the way. We are updating content to make the use of arrows more obvious. Thank you for reporting this issue.

**Comment by ericnakagawa** [comment]
New build deployed.
